### ISSUE TITLE
Definition for xml-list is missing

### ISSUE THREAD

**Issue by avtobiff** [netconf-wg/list-pagination#13]
The definition for xml-list is missing in list-pagination, it is referenced
in both -nc and -rc drafts and also used in examples.

**Comment by kwatsen** [comment]
There is a definition for "xml-list" in the lp-rc draft, which makes me think that its presence in the lp-nc draft is an error...I think the NC rpc-reply wraps the payload with an XML element, so perhaps returning the raw XML-list would be okay? (i.e., more than one top-level XML element) 

I'm trying to fix the lp-rc draft examples now.
Fixing the lp-nc issue will have to wait.

**Comment by avtobiff** [comment]
Yes, it is probably an error in NC draft of course.
It is wrapped in <data> in NETCONF, but RESTCONF
doesn't always produce a top level tag.

**Comment by kwatsen** [comment]
I just pushed updates for both the -nc and -rc drafts fixing the validation issues - closing this issue.
