### ISSUE TITLE
incomplete text around 'cursor' and 'locale'

### ISSUE THREAD

**Issue by kwatsen** [netconf-wg/list-pagination#20]
The spec should be clarify:

  - `local` has no affect if `sort-by` is unspecified
  - `offset` and `cursor` are mutually exclusive
  - `limit` is applied after `offset` *and* after `cursor`

Also, the spec uses words "collating" and "collation".  I suggest switching these to "sorting" and "sorts", to align with the name of the query parameter.

**Comment by flycoolman** [comment]
This will make the text more specific and easier for reading and implementation.

- local has no affect if sort-by is unspecified
// can be added to the section of "locale"
- offset and cursor are mutually exclusive
// can be added to the section of "offset" and "cursor"
- limit is applied after offset and after cursor
// This is implied in the section of "The order is as follows:"

Also, the spec uses words "collating" and "collation". I suggest switching these to "sorting" and "sorts", to align with the name of the query parameter.
// Agreed. Particularly align with " locale has no affect if sort-by is unspecified"

**Comment by avtobiff** [comment]
> * local has no affect if sort-by is unspecified
> // can be added to the section of "locale"
> * offset and cursor are mutually exclusive
> // can be added to the section of "offset" and "cursor"
> *  limit is applied after offset and after cursor
> // This is implied in the section of "The order is as follows:"

Agree with these. Please provide text.


> * Also, the spec uses words "collating" and "collation". I suggest switching these to "sorting" and "sorts", to align with the name of the query parameter.
> // Agreed.

Agree, please provide text.


> Particularly align with " locale has no affect if sort-by is unspecified"

Do not agree with this. The current text states that
if the list is actually sorted according to some locale
and emitted as such (i.e. in that locale order selected
by the server) even if when sort-by is not used, locale
should be reported by the server.

See #18. Note that it is already merged.

**Comment by flycoolman** [comment]
> Do not agree with this. The current text states that
if the list is actually sorted according to some locale
and emitted as such (i.e. in that locale order selected
by the server) even if when sort-by is not used, locale
should be reported by the server.

It's true. The locale is reported and he output is in system order. Locale does not have effect on the order.

**Comment by avtobiff** [comment]
> The locale is reported and he output is in system order. Locale does not have effect on the order.

Unsure what you mean.  If the system order means that it is sorted
according to a locale (say en_US), then that should be reported in
the output.

That is at least the intention by the text in the draft.

**Comment by avtobiff** [comment]
> * offset and cursor are mutually exclusive
> // can be added to the section of "offset" and "cursor"

This is alreday described in the processing order.
