### ISSUE TITLE
Make "where" example A.3.6.2 more interesting 

### ISSUE THREAD

**Issue by avtobiff** [netconf-wg/list-pagination#23]
In a mail thread Olof raises:
> The "where" match in A.3.6.2 matches all entries. The example could
> be made more interesting if one uses another match, or change one of the
> member's email to something else than example.com.

I suggest one of the member use e.g. example.org.

**Comment by flycoolman** [comment]
Agreed. The response should be a subset of the example data set. The example.org may need reader to take a close look, i.e. social.org, or abc.com might be more obvious.

**Comment by avtobiff** [comment]
RFC 6761 has a number of example domains which
can't be registered.

Perhaps something like `user.example.net` is
easier to spot.

**Comment by flycoolman** [comment]
Agree with using example.net. Then we need to add a member to the data set or change some of the current members in the data set.
