### ISSUE TITLE
Example list is ordered-by system, might need change

### ISSUE THREAD

**Issue by avtobiff** [netconf-wg/list-pagination#24]
> 2) In the same example data set, the members/member list is (by default)
> ordered-by system. This is problematic in some example results that are
> not explicitly sorted, such as A.3.6.2+.3 Here, the result order is
> given as (bob,eric,alice,lin,joe) which happens to be the same order as
> they are given in the example set, but ordered-by system does not
> mandate this. In our implementation, for example, the entries would be
> returned in alphabetical order of the keys (alice,bob,eric,joe,lin).
> Further, the response order in A.3.6.2 is (bob,eric,alice,joe,lin) which
> is neither alphabetical or as in the original order.
> One could add "ordered-by user" to resolve this, alt state that the
> order is not significant in the results given.

**Comment by flycoolman** [comment]
We can say the results showed in the system order and not significant. This complies with the system order, since no sort-by.

**Comment by avtobiff** [comment]
That might be enough. I'm ok with it.
